### ISSUE TITLE
Ubuntu box cannot be downloaded - no longer available

### ISSUE THREAD

**Issue by edgarvonk** [nicolasbarbe/magnolia-vagrant#2]
Hi Nicholas,

The Ubuntu box in the Vagrantfile (https://cloud-images.ubuntu.com/vagrant/utopic/current/utopic-server-cloudimg-amd64-vagrant-disk1.box) seems no longer available. "The requested URL returned error: 404 Not Found". In fact the 'utopic' builds seem to have disappeared altogether: https://cloud-images.ubuntu.com/vagrant/

So I changed the Vagrantfile to use the Ubuntu Vivid release instead:

```
override.vm.box = "ubuntu/vivid64"
override.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/vivid/current/vivid-server-cloudimg-amd64-vagrant-disk1.box"
override.vm.box_download_checksum = "502923c3aeb0ce101fa783585c37e38d"
override.vm.box_download_checksum_type = "md5"
```

PS: we want to use CoreOS instead of Ubuntu to run Magnolia in. Do you have any experience with that?

cheers

Edgar

**Comment by nicolasbarbe** [comment]
Thanks for pointing this! It is fixed now.
